public enum TokenType{
	NUMBER, NEWLINE, OPERATOR, EOF, UNKNOWN, ADD, SUBTRACT,
	MULTIPLY, DIVIDE, LEFT_PAREN, RIGHT_PAREN, ASSIGNMENT,
	LESS, GREATER, EQUAL, NOTEQUAL, LESSEQUAL, GREATEREQUAL,
	NOT, OR, AND, KEYWORD, PRINT, PRINTLN, WAIT, END, SCRIPT,
	STRING, WHILE, IF, ELSE, RIGHT_BRACKET, LEFT_BRACKET, COMMA
}